version: '3.5'
services:

  db-currency:
    container_name: db_currency
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_DB: currency
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - postgres-pg-admin

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:7.2
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@kiok.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    ports:
      - "5050:80"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d distribution" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - postgres-pg-admin

networks:
  postgres-pg-admin:
    driver: bridge
